name: PR Test

on:
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: Run CLI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./cli start
      - run: ./cli tests
